### ISSUE TITLE
Use raw meta values in a `raw_meta` property only, and not as properties on the class itself.

### ISSUE THREAD

**Issue by jarednova** [timber/timber#1823]
See comments in #1809.

### Acceptance Criteria
- [x] `Post::raw_meta` returns an array of properties with the data stored in the `wp_postmeta` table. The data should be unprocessed by ACF and other plugins (probably the same as what's returned from WP's native functions)
- [x] Can utilize existing performance overhead (no new queries, etc.)
- [x] Preserve current behavior where fetching data using magic `__get` DOES return the ACF-processed data (current behavior)

**Comment by gchtr** [comment]
@jarednova I have some questions, because I’m not sure what you envisioned here exactly. 

## raw_meta and/or custom?

In https://github.com/timber/timber/pull/1809, you write:

> For `2.x` this could impact how we handle custom field data. I've found that it's MUCH easier/cleaner here if those fields are retrieved at runtime (ie `{{ post.meta("my_field") }}`) vs. initialization (where the data is attached to the `Timber\Post` object before it's even fetched).

> I think it's still sufficient to leave those raw values inside the `custom` property. Is there another word that makes more sense? `{{ post.raw_meta }}` ?

Will `raw_meta` replace the `custom` property? If yes, should we properly deprecate the `custom` property or make this a breaking change and just delete the `custom` property? Or is `raw_meta()` a method that accesses the `custom` property? Or is `raw_meta` both a method and a property? Should single values be accessible through `post.raw_meta('field_name')` as well as `post.raw_meta.field_name`?

## Populate the object with raw meta values on initialization?

In https://github.com/timber/timber/pull/1618#issuecomment-354575795, I wrote:

> So the values are still loaded from the database and added to the `custom` property. When using `__get()`, is Timber (or WordPress) retrieving a cached value? Otherwise, should `Timber\Core::__get()` or the `meta()` method check for a custom property and return that value?

To which you answered:

> you are right about the `custom` property. As it turns out, those values are cached so we get them for "free" (at least, that was based on my earlier tests about a year ago so assuming nothing changed).

Currently, we don’t check for an already retrieved value in `Timber\Post::meta()`. We always get it from the database through `get_post_meta()`. Do we really get raw values for free? What if somebody only wants to access one meta value of a post that should be filtered in the template? Will the population of the object with raw values run for nothing?

I see two ways to go here:

1. Deprecate that the post object gets populated with raw meta values on initialization and only use `raw_meta()` to access raw properties. Let WordPress do all the performance optimization.
2. Keep fetching all raw meta values, and optimize `meta()` to access the raw values instead of fetching them from the database. I guess there would be no drawbacks, because we’d use `get_post_custom()`, which directly uses `get_post_meta()`.

And what do you mean with the following acceptance criteria?

> Can utilize existing performance overhead (no new queries, etc.)

## Example for what we want to have

Can we define examples for how custom values should accessed in the same way that we did in https://github.com/timber/timber/pull/1618#issuecomment-354627351? In my opinion, the following public API would be a good way to go:

### `{{ post.meta('my_field') }}`

This is the recommended way to get custom values. The values are filtered by ACF or other custom fields plugins. There’s no risk in accessing a field that has the same name as a Timber method (e.g. `title`).

### `{{ post.my_field }}`

This is the shorthand form of `meta()`, which will hit `__get()`. The values are filtered by ACF or other custom fields plugins. ~This will probably be what people use/want in 99% of situations.~ Usage still works, but it’s not recommended, because there might be conflicts with existing Timber methods or properties. This will be deprecated in an upcoming version of Timber.

### ``{{ post.raw_meta('my_field') }}``

This is the recommended way of accessing raw meta values straight from the `postmeta` table.

### ~`{{ post.custom.my_field }}`~

~This is recommended if the dev wants the values straight from the `postmeta` table.~ Accessing a value through the `custom` property is not possible anymore, because it was confusing that it did exactly. Depending on what we decide above, the `custom` property will just be a protected property for internal usage, or not exist at all.

**Comment by jarednova** [comment]
@gchtr some changes/final things after resolving #478 

### Examples for what we want to have

### `{{ post.meta('my_field') }}`
This is the recommended way to get custom values. The values are filtered by ACF or other custom fields plugins. There’s no risk in accessing a field that has the same name as a Timber method (e.g. title).

### `{{ post.my_field }}`
As discussed in #478 — we're going to remove dynamic properties. The time this would be used is when someone has a custom property or method on their `Timber\Post` subclass

### `{{ post.raw_meta('my_field') }}`
This is the recommended way of accessing raw meta values straight from the `postmeta` table.

### ~~`{{ post.custom.my_field }}`~~
This should never appear in a Twig template. However, I recommend we preserve this as a protected property so that a developer can do a `{{ dump(post) }}` to see what custom fields exist on their post.

**Comment by gchtr** [comment]
@jarednova Alright. That sounds good! Now I can start to work on this 👍.

**Comment by gchtr** [comment]
@jarednova Quick question: In https://github.com/timber/timber/pull/1583#issuecomment-339857286, you [added logic](https://github.com/timber/timber/commit/66878b94d876b5c3f293fe28a666e2068b6328ee) for the `gallery()`, `video()` and `audio()` methods to check whether a  `$custom` property with the same name exists. For example:

https://github.com/timber/timber/blob/a525319ce55800143f264c58f656e4992cd47f36/lib/Post.php#L1543-L1555

With the new approach that says that meta values should be accessed through `{{ post.meta('video') }}`, wouldn’t it make sense to remove these checks? Then, `{{ post.video }}` should only be used if someone wanted to fetch video from the post’s content. Or they could define their own `video()` method in a child class of `Timber\Post`.

The same goes for the [`type()` method](https://github.com/timber/timber/commit/6c9574912e526b8589eb134b79820c7e239a1dda). I would remove the check for `$custom` as well.

What do you think?

**Comment by jarednova** [comment]
yeah, good catch — those are great examples of the remnants of the 1.x style that we should take care of here. Can you take removing those?

**Comment by gchtr** [comment]
@jarednova Cool, yep, I’ll remove those.

**Comment by gchtr** [comment]
Closed via #1904.
