### ISSUE TITLE
Timber 2.0 and the plugin version

### ISSUE THREAD

**Issue by Levdbas** [timber/timber#2794]
With 2.0 around the corner. We would like to see people trying out Timber 2.0 in their projects. But from a response lately:
> What about support for the Timber plugin? Will the plugin be updated with the release of Timber 2.0?
> 
> I have some older sites that are using the plugin and we are not able to switch to installing Timber in our theme at this time.

_Originally posted by @okadots in https://github.com/timber/timber/issues/2793#issuecomment-1718297524_
            
We can see that there is quite some attention for the removal of the plugin version.

### Why we are dropping support for installing Timber 2.0 as a plugin
In #2005 @gchtr lays out why we are dropping the plugin support. The main takeaways:

- Timber was never a "plugin", so easy to update with the press of a button in the admin environment.
- Supporting Timber also as a plugin makes it harder to introduce breaking changes. Since Timber 2.0 introduces a lot of breaking changes, this was an issue as well.

### What we have to do to signal the big upcoming change
As stated by @rmens 

>  Should there be a big fat warning on the plug-in page on Wordpress.org that it’s essentially sunset? You don’t want people starting with it with 2.0 around the corner.

_Originally posted by rmens in https://github.com/timber/timber/issues/2793#issuecomment-1718834444_

It might be a good idea to make to changes to the readme of [Timber on WordPress.org](https://nl.wordpress.org/plugins/timber-library/) to signal people to migrate over to the composer version of Timber instead.

@gchtr and @jarednova , what is your take on this?

### What you, the people using Timber need to make the transition
We would like to know what is holding you back making the switch to the composer version of Timber. We cannot promise to take all issues into consideration but if we spot some clear trends as of why people haven't made the transition yet, we might be able to write some extra documentation, make a video, or something along those lines. 

### TODOs for phasing out the plugin version

- [x] Update the Timber page at [Upstatement](https://upstatement.com/timber/). Primarily update the install link. @jarednova (change is made and should be deployed in the next few days)
- [x] Pinned issue in https://wordpress.org/support/plugin/timber-library/ @jarednova , I think you have admin access to the plugin at wp.org
- [ ]  [PR pending - create documentation for the upgrade path from switching from the plugin version to the composer version.](https://github.com/timber/timber/pull/2800)
- [ ] PR pending - Add a notification in the plugin row with a message about the support ending for the plugin
- [ ] PR pending - Update the readme.txt and add a message there as well so it ends up at the [plugin wp.org page](https://nl.wordpress.org/plugins/timber-library/)
- [ ] PR pending- Update 1.x docs
- [ ] PR pending - Add message in [readme.md](https://github.com/timber/timber/blob/master/README.md) in main branch

**Comment by jarednova** [comment]
Some additional color and context here: the team at the WordPress.org Plugin repo asked us to phase out Timber as a plugin. They said that under current guidelines Timber could not be approved as a plugin, thus submitting a fresh 2.0 version is unfortunately not in the cards.

**Comment by jrathert** [comment]
Now that I have migrated from Timber plugin to Timber v2.0-rc.1 (at least in my dev-environment) I can only say what kept me before from doing so:

- The whole status/description of the currently Timber plugin is quite vague about if it is supported, if it still works with newer versions of WordPress/PHP etc. 
  - When you have an older version installed (I have 1.20.0) in the WP backend it does not automatically update to the newest version (which according to the doc is not tested with the current WP version!). 
  - The statement about why and when to do the update manually is quite complex and hard to understand. Looking into the details, one can see that some work has been done, e.g., the support for PHP 8.1 was removed (?!) etc. There is little mentioning of an upcoming version 2.0 of a plugin and especially the when and how. 
  - So it simply looks a bit as if just staying what you have installed and works is simply the best of all solutions. 
- My theme was developed by an agency a while ago. For whatever reason they do not really support us any more. I can only assume that there are many installations out there with a similar problem, also given the fact that v1 exists since quite some time already.
- The upgrade documentation could be a bit clearer. 
  - I found a few things very easy (e.g., no more `Timber\Post` but `Timber:get_post()`) and a few very hard (e.g. handling of custom types, the need for a `meta()`-call, handling images etc.)
  - Regarding many of the before-now sections, it is not clear if it is a mandatory change (for some it is clearly explained) or just the "this is how you SHOULD do it" and it would work if you do not change it at all. That makes the task look quite big.
- Maybe simply some people are not used to `composer` (hard to believe)?

What might be a good thing is to have / allow a step-by-step-guide for people using the plugin:
- make a copy of your theme
- change into its directory and do a `composer require timber/timber:2.0.0-rc.1`
- do the MUST-changes (e.g. no-more-working initialization, etc.)
- deploy on a dev site where there is no plugin installed
- check what works and what not
I more or less followed an approach like that, but maybe it would be helpful to suggest this explicitly.

Hope this helps a bit.

**Comment by Levdbas** [comment]
Hi @jrathert ,

Thank you for taking the time to give us some insights on your upgrade process. I totally agree that a step-by-step guide should come in handy. As for the upgrade path now I think about it, it might be better for people to upgrade from Plugin to Timber 1.x composer version. See if that runs as expected, and then upgrade to 2.0. This way it is easier to pinpoint any problem that might occur.

I will make an additional TODO for this. If you would like to help us a hand here, you are more then welcome to create a PR for the additional documentation.
