### ISSUE TITLE
Release checklist for 1.23.1

### ISSUE THREAD

**Issue by gchtr** [timber/timber#2966]
## readme.txt
- [x] Update changelog info
- [x] Update "Test up to" version
- [x] Update Stable tag

## GitHub
- [x] Publish Release, see https://github.com/timber/timber/releases/tag/1.23.1

## PHP files
- [x] Update version in `lib/Timber.php`
- [x] Update version in `bin/Timber.php`

## Deploy to WordPress.org

> [!IMPORTANT]
> Please be aware that version 1.23.1 is tagged on the [`wp-plugin`](https://github.com/timber/timber/tree/wp-plugin) branch and not on the `1.x` branch!

- [x] Run `./bin/deploy-to-wp-org 1.23.1`
- [x] Publish new tag for version
- [x] Update `trunk`

## Twitter
- [x] Tweet it out!

> We just released new Timber versions with a security fix for the plugin and the Composer version of Timber 1.x as well as for Timber 2.x. Please update Timber as soon as you can!
>
> The fixed vulnerability only appears only on PHP versions 7.4 or lower.
>
> Check the release notes for more details: https://github.com/timber/timber/releases/tag/2.1.0

**Comment by jarednova** [comment]
all set! https://twitter.com/TimberWP/status/1778400305127809328
